# Generated by Django 3.2.3 on 2021-06-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=10)),
                ('cell', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('member_organization', models.CharField(max_length=50)),
            ],
        ),
    ]
