# Generated by Django 3.2.3 on 2021-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='member_organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
