# Generated by Django 3.2.4 on 2021-06-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cell',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='member_organization',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='street_address',
            field=models.CharField(max_length=75),
        ),
    ]
