# Generated by Django 3.2.4 on 2021-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('username', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('streetAddress', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('memberOrganization', models.CharField(max_length=75)),
            ],
        ),
    ]
